version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus  # Persistent storage for Prometheus data  
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Config file
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana # Persistent storage for Grafana data 
      - /var/log:/var/log  # Mount system logs if needed
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki-local
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki  # Persistent storage for Loki data
      - ./loki-config.yaml:/etc/loki/loki-config.yaml  # Config file  
    command: -config.file=/etc/loki/loki-config.yaml
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - alloy-data:/var/lib/alloy/data  # Persistent storage for Alloy data
      - ./config.alloy:/etc/alloy/config.alloy # Config file
      - /var/run/docker.sock:/var/run/docker.sock 
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:
  loki-data:
  alloy-data:
